dist: releases
snapshot:
  name_template: '{{ trimprefix .Summary "v" }}'

before:
  hooks:
    # Generate UI assets to embedded in binaries
    - make build-ui
    - ./scripts/download-cred-helpers.sh

builds:
  - id: default
    binary: gptscript
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X "github.com/gptscript-ai/gptscript/pkg/version.Tag=v{{ .Version }}"
    hooks:
      post: ./scripts/copy-cred-helper.sh {{ .Os }} {{ .Arch }}

universal_binaries:
  - id: mac
    ids:
      - default
    replace: true
    hooks:
      post: cp binaries/gptscript-credential-osxkeychain releases/mac_darwin_all

archives:
  - id: default
    builds:
      - default
      - mac
    name_template: 'gptscript-v{{ .Version }}-{{ if eq .Os "darwin" }}macOS-universal{{ else }}{{ .Os }}-{{ .Arch }}{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^Merge pull request"

release:
  github:
    owner: gptscript-ai
    name: gptscript
  prerelease: auto

brews:
  - description: "GPTScript CLI"
    install: |
      bin.install "gptscript"
      {{ if eq .Os "darwin" }}bin.install "gptscript-credential-osxkeychain"{{ end }}
    homepage: "https://github.com/gptscript-ai/gptscript"
    skip_upload: true
    folder: "Formula"
    repository:
      owner: gptscript-ai
      name: homebrew-tap
      token: "{{ .Env.GH_PROJECT_TOKEN }}"
