name: test

on:
  push:
    branches:
      - main
    paths-ignore:
      - docs/**
  pull_request:
    branches:
      - main
    paths-ignore:
      - docs/**

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version: "1.21"
      - name: Build UI
        run: |
          if [ ${{ matrix.os }} != 'windows-latest' ]; then
            make build-ui
          fi
        shell: bash
      - name: Validate
        run: | 
          if [ ${{ matrix.os }} != 'windows-latest' ]; then
            make validate
          fi
      - name: Build
        run: make build
      - name: Run Tests
        run: make test
